server.port=8080

file-storage:
  provider: aliyun-oss
  bucket: leite
  endpoint: oss-cn-hangzhou.aliyuncs.com
  access-key-id: ${ALIBABACLOUD_ACCESS_KEY_ID:YOUR_ACCESS_KEY_ID}
  access-key-secret: ${ALIBABACLOUD_ACCESS_KEY_SECRET:YOUR_ACCESS_KEY_SECRET}
  cdn-domain: https://cdn.leite.com
  default-expire-minutes: 60
  multipart-threshold: 10485760
  multipart-part-size: 5242880
